server {
    listen 80;
    server_name price.scor.vip;  # 支持主域名和www

    # 静态文件配置
    root /var/www/price.scor.vip;
    index index.html;

    access_log /var/log/nginx/price.scor.vip.access.log;
    error_log /var/log/nginx/price.scor.vip.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    # 可选：禁止访问.git等敏感目录
    location ~ /\.(git|env) {
        deny all;
        return 404;
    }
}
